os: Visual Studio 2015 CTP  
version: 1.1.0.{build}

configuration:
- Debug
- Release

environment:
  matrix:
   - VS_VERSION: 9 2008
     VS_PLATFORM: win32
   - VS_VERSION: 9 2008
     VS_PLATFORM: x64
  #- VS_VERSION: 10 2010
  #  VS_PLATFORM: win32
  #- VS_VERSION: 10 2010
  #  VS_PLATFORM: x64
  #- VS_VERSION: 11 2012
  #  VS_PLATFORM: win32
  #- VS_VERSION: 11 2012
  #  VS_PLATFORM: x64
  #- VS_VERSION: 12 2013
  #  VS_PLATFORM: win32
  #- VS_VERSION: 12 2013
  #  VS_PLATFORM: x64
   - VS_VERSION: 14 2015
     VS_PLATFORM: win32
   - VS_VERSION: 14 2015
     VS_PLATFORM: x64
  #- VS_VERSION: 15 2017
  #  VS_PLATFORM: win32
  #- VS_VERSION: 15 2017
  #  VS_PLATFORM: x64
before_build:
- git submodule update --init --recursive
- cmake -H. -Bbuild/vs -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM%

build:
  project: build\vs\dmtimer.sln
  parallel: true
  verbosity: minimal

test_script:
- echo %APPVEYOR_REPO_NAME%
 # - cd Build\VS && if %CONFIGURATION%==Debug (ctest --verbose -E perftest --build-config %CONFIGURATION%) else (ctest --verbose --build-config %CONFIGURATION%)
